import { HttpStatus } from '@nestjs/common';

/** Catalogo central de codigos de error. Un codigo que no este aqui no existe. */
export const CODIGOS = {
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  NO_AUTENTICADO: HttpStatus.UNAUTHORIZED,
  SESION_INVALIDA: HttpStatus.UNAUTHORIZED,
  SESION_EXPIRADA: HttpStatus.UNAUTHORIZED,
  SESION_REVOCADA: HttpStatus.UNAUTHORIZED,
  CREDENCIALES_INVALIDAS: HttpStatus.UNAUTHORIZED,
  CSRF_INVALIDO: HttpStatus.FORBIDDEN,
  FIRMA_INVALIDA: HttpStatus.UNAUTHORIZED,
  SIN_PERMISO: HttpStatus.FORBIDDEN,
  USUARIO_INACTIVO: HttpStatus.FORBIDDEN,
  RECURSO_NOT_FOUND: HttpStatus.NOT_FOUND,
  CREDITO_NOT_FOUND: HttpStatus.NOT_FOUND,
  USUARIO_NOT_FOUND: HttpStatus.NOT_FOUND,
  CUOTA_NOT_FOUND: HttpStatus.NOT_FOUND,
  CREDITO_DUPLICADO: HttpStatus.CONFLICT,
  USUARIO_DUPLICADO: HttpStatus.CONFLICT,
  CONCURRENCIA_CONFLICTO: HttpStatus.CONFLICT,
  TRANSICION_INVALIDA: HttpStatus.UNPROCESSABLE_ENTITY,
  REGLA_NEGOCIO: HttpStatus.UNPROCESSABLE_ENTITY,
  CREDITO_INMUTABLE: HttpStatus.UNPROCESSABLE_ENTITY,
  DEMASIADAS_PETICIONES: HttpStatus.TOO_MANY_REQUESTS,
  ERROR_INTERNO: HttpStatus.INTERNAL_SERVER_ERROR,
} as const;

export type CodigoError = keyof typeof CODIGOS;
